server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: darkmario
    url: jdbc:mysql://0nrbswc3.2280.dnstoo.com:5505/darkmario?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: darkmario_f

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.DarkMario.blog.entity  # 注意：对应实体类的路径
    